Styling
sumancrest0001/Apple-clone pull request #2
Opened 2019-08-02 15:24 UTC by sumancrest0001

2019-08-02 17:51 UTC, mosaaleb commented
Reviewing

2019-08-02 20:07 UTC, mosaaleb requested changes
### Hi @sumancrest0001 :wave:

#### Good job :clap:. You have met most of the requirements, yet there is minor requirements we need to work on before moving on.

Please see my comments below.

**Also** Let's add [stickler](https://github.com/microverseinc/linters-config/tree/master/css) to make sure that our code have good style guidelines.

Please handle these requirements and submit a new code review.

#### Happy Coding :computer:

2019-08-02 20:07 UTC, mosaaleb commented on index.html
> +                        <span></span>
There is no written styles for these classes in the css file `nav-items logo store mac ipod ...`. We can remove them if they don't do anything.

2019-08-02 20:07 UTC, mosaaleb commented on index.html
> +                                    <i class="fa fa-search"></i><input type="text" name="search">
For simple UI components like [search field](https://stackoverflow.com/questions/3294572/is-input-well-formed-without-a-form), there is no need to add `<form>` tag. `<input>` tag would be enough.

2019-08-02 20:07 UTC, mosaaleb commented on index.html
> +            </div>
Main content links (the three text):
- [ ] Each link is an `<a>` HTML tag, with a `<div>` tag inside it.
- [ ] The `<div>` tag  inside the `<a>` tag should use an image as background -- [ ] The text on the original page is actually an image

2019-08-02 20:07 UTC, mosaaleb commented on index.html
> +            <div class="articles article-2"><a href="#"><img src="images/second-article.jpg" alt="second article"></a></div>
The four promo images part:
- [ ] Is made of four `<a>` tags with `<div>` tags inside it
- [ ] The `<div>`s inside the `<a>` tags should use an image as a background, [why `bacground-image` and not `<img>` tag](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image)

2019-08-09 00:41 UTC, Torres-ssf commented
### Nicely done @sumancrest0001 :+1: 

I notice that you fixed the stickler file in a separate branch but would be better if you merged to this current branch instead of merging to master since it needs to look for errors in the project before merging to master. The silver lining here is that you already know how to set up the linter :muscle: . We need to fix that. Please make the linter work in this branch so we can see if your code has no errors. I know that in the past we didn't pay much attention to it but linting is important to reduce errors and improve the overall quality of your code. 


- For Future Projects

- [ ] You should use Github/Git Flow in future projects. It's really easy to use it and will make your repository looks more professional. You will find instructions in the Patwright lesson description.

Kindly make this change and submit for code review again.

2019-08-10 00:14 UTC, mosaaleb approved these changes
## Amazing work @sumancrest0001 :clap:

You can merge into master :+1: 

While all the checks gives warning and not failures. Let's make sure in the coming project we handle all the warning also. 

Let's make sure from the next project that we follow the github/git flow instructions in your pathwright.

Good luck with the next projects

#### Happy Coding :computer:

2019-08-13 22:43 UTC, merged